### PR TITLE
Add regression tables for current MF versions

### PR DESCRIPTION
**Pull request by namapane**
These binary files contain reference values for regression tests of currently supported MF versions.

### CODE REVIEW

**Comment by slava77** [comment]
> These binary files contain reference values for regression tests of currently supported MF versions.

@namapane 
Please add a  README.md or a similarly named file with a description of the content and the format of the binary files.
Thank you.

**Comment by slava77** [comment]
+1

@namapane 
thank you for the quick update.

@smuzaffar @fabiocos 
the PR looks in line with the earlier discussion by email. I think that we can merge it already.

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Pull request merged**
